# Generated by Django 5.2.6 on 2026-01-03 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Body', 'Body'), ('Hair', 'Hair'), ('Makeup', 'Makeup')], max_length=6)),
                ('expiration_date', models.DateField(blank=True)),
                ('is_expired', models.BooleanField()),
                ('finish_date', models.DateField(blank=True)),
                ('is_finished', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
