# Generated by Django 5.2.6 on 2026-01-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
